import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

final List<Icon> changasIcons = [
  const Icon(FontAwesomeIcons.hammer),
  const Icon(FontAwesomeIcons.key),
  const Icon(FontAwesomeIcons.personDigging),
  const Icon(FontAwesomeIcons.bookOpenReader),
  const Icon(FontAwesomeIcons.cat),
  const Icon(FontAwesomeIcons.personCane),
  const Icon(FontAwesomeIcons.spoon),
  const Icon(FontAwesomeIcons.trowelBricks),
  const Icon(FontAwesomeIcons.plugCircleBolt),
  const Icon(FontAwesomeIcons.bugSlash),
  const Icon(FontAwesomeIcons.fire),
  const Icon(FontAwesomeIcons.screwdriverWrench),
  const Icon(FontAwesomeIcons.pagelines),
  const Icon(FontAwesomeIcons.car),
  const Icon(FontAwesomeIcons.hands),
  const Icon(FontAwesomeIcons.spa),
  const Icon(FontAwesomeIcons.shirt),
  const Icon(FontAwesomeIcons.truck),
  const Icon(FontAwesomeIcons.paintRoller),
  const Icon(FontAwesomeIcons.personSwimming),
  const Icon(FontAwesomeIcons.droplet),
  const Icon(FontAwesomeIcons.snowflake),
  const Icon(FontAwesomeIcons.screwdriverWrench),
  const Icon(FontAwesomeIcons.computer),
  const Icon(FontAwesomeIcons.peopleRoof),
  const Icon(FontAwesomeIcons.broom),
  const Icon(FontAwesomeIcons.couch)
];

final List<String> changasDescription = [
  'Carpintería',
  'Cerrajería',
  'Construcción',
  'Clases de inglés',
  'Cuidado de Mascotas',
  'Cuid. Ancianos/Niños',
  'Depilación',
  'Durlock',
  'Electricidad',
  'Fumigaciones',
  'Gasista',
  'Herrería',
  'Jardinería',
  'Limpieza de Autos',
  'Manicura y Uñas',
  'Masajes',
  'Modista',
  'Mudanzas',
  'Pintura',
  'Piscinas',
  'Plomería',
  'Refrigeración/AA',
  'Rep. de Electrodom.',
  'Rep. de PC',
  'Reparación de Techos',
  'Servicio Doméstico',
  'Tapicería'
];
